config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  root 'home#landing'

  resources :users do
    get :public_profile, on: :member
  end

  resources :places, only: [:new, :create]

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
end

app/models/shared_place.rb
class SharedPlace < ActiveRecord::Base
  has_many :user_shared_places, dependent: :destroy

  geocoded_by :address
  after_validation :geocode

  validates :street_address, :state, :country, presence: true

  def address
    [street_address, state, country, zip_code].reject(&:blank?).join(", ")
  end

  def build_share_locations(params, user)
    if params[:share_via] == "all"
      user_shared_places.build(public: true, user_id: user.id)
    elsif params[:share_via] == "friend"
      params[:friend_ids].each do |friend_id|
        user_shared_places.build(user_id: user.id, friend_id: friend_id)
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, source: :friend

  has_many :user_shared_places, dependent: :destroy
  has_many :shared_places, through: :user_shared_places
  has_many :public_shared_places, -> { where(user_shared_places: {public: true}) }, through: :user_shared_places, source: :shared_place

  has_many :places_shared_with_friends, -> { where("user_shared_places.friend_id is not null") }, through: :user_shared_places, source: :shared_place

  validates :first_name, :email, :username, presence: true
  validates :password, presence: true, on: :create
  validates :password, confirmation: true, on: :create
  validates :email, :username, uniqueness: true

  def name
    [first_name, last_name].compact.join(" ")
  end

  def grouped_shared_places_for_friends
    user_shared_places.for_friends.group_by(&:address)
  end

  def places_shared_with_user
    UserSharedPlace.where(friend_id: id, public: false)
  end

  def grouped_places_shared_with_user
    places_shared_with_user.group_by(&:address)
  end
end

app/models/user_place.rb
class UserPlace < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
end

app/models/user_shared_place.rb
class UserSharedPlace < ActiveRecord::Base
  belongs_to :user
  belongs_to :shared_place
  belongs_to :friend, class_name: "User", foreign_key: :friend_id

  scope :for_friends, -> { where("friend_id is not null") }
  scope :for_public, -> { where(public: true) }

  delegate :address, :latitude, :longitude, to: :shared_place

  validates :user, :shared_place, presence: true

  def friend_name
    friend.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :password, :password_confirmation, :street_address, :first_name, :last_name, :username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def landing
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_filter :authenticate_user!

  def new
    @place = current_user.shared_places.build
  end

  def create
    @place = current_user.shared_places.build(place_params)

    if params[:share_via] == "friend" && params[:friend_ids].blank?
      flash.now[:warning] = "Please select friends"
      render :new and return
    end

    if @place.valid?
      @place.build_share_locations(params, current_user)
      @place.save
      flash[:success] = "Location added successfully"
      redirect_to user_path(current_user)
    else
      flash.now[:warning] = @place.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def place_params
    params.require(:shared_place).permit(:street_address, :zip_code, :state, :country)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    user_path(current_user) # Or :prefix_to_your_route
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  protected

  def after_sign_in_path_for(resource)
    user_path(current_user) # Or :prefix_to_your_route
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: :public_profile

  def index
    @users = User.all
  end

  def show
    @user = User.includes(:friends, user_shared_places: [:shared_place, :friend]).find(current_user.id)
    @friends = @user.friends
    @shared_places_data = (@user.user_shared_places + @user.places_shared_with_user).to_json(only: [:public, :friend_id], methods: [:latitude, :longitude, :address])
  end

  def public_profile
    @user = User.where(username: params[:id]).first
    @public_places = @user.public_shared_places.to_json(only: [:latitude, :longitude, :address])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def name(user)
    if user == current_user
      "Me"
    else
      user.first_name
    end
  end
end

app/views/home/landing.html.erb
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Pri quas audiam virtute ut, case utamur fuisset eam ut, iisque accommodare an eam. Reque blandit qui eu, cu vix nonumy volumus. Legendos intellegam id usu, vide oporteat vix eu, id illud principes has. Nam tempor utamur gubergren no.
</p>
<div class="text-center">
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

      <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDdR7Fspo10latUCGXxEJzNsxKulGcoDJI&callback=initMap">
      </script>

    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
	          </button>
	          <%= link_to "My Sample App", root_path, class: "navbar-brand" %>
	        </div>
	        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	          <ul class="nav navbar-nav navbar-right">
	            <% unless signed_in? %>
	            <li><%= link_to "Sign Up", new_user_registration_path %></li>
	            <li><%= link_to "Sign In", new_user_session_path %></li>
	            <% else %>
              <li><%= link_to "Profile", user_path(current_user) %></li>
	            <li><%= link_to "Sign Out", destroy_user_session_path,
	                    method: :delete %></li>
	            <% end %>
	          </ul>
	        </div>
        </div>
      </nav>
      <div class="container-fluid">
	      <% flash.each do |key, value| %>
        <div class="alert bg-<%= key %>"><%= value %></div>
	      <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/places/new.html.erb
<h2>Share Location</h2>

<%= form_for @place, url: places_path do |f| %>
  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country, class: "form-control country-dropdown", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control country-dropdown", required: true  %>
   </div>

  <div class="field form-group">
    <%= f.label :street_address %><br />
    <%= f.text_field :street_address, class: "form-control", required: true %>
  </div>

  <div class="field form-group">
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code, class: "form-control" %>
  </div>

  <label>Share With</label>
  <div class="radio">
    <label><%= radio_button_tag "share_via", "all", checked: true %>Public</label>
  </div>

  <% if current_user.friends.present? %>
  <div class="radio">
    <label><%= radio_button_tag "share_via", "friend" %>Friends</label>
  </div>

  <div id="friend-list" class="form-group hide">
    <label>Select Friends</label>
    <%= select_tag :friend_ids, options_from_collection_for_select(current_user.friends, :id, :name), multiple: true, class: "form-control" %>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<table class="table">
  <thead>
    <tr>
	    <th>Name</th>
	    <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
	    <td><%= link_to user.name, user_path(user) %></td>
      <td><%= link_to "Edit", edit_user_path(user) if user == current_user %></td>
	  </tr>
    <% end %>
  </tbody>
</table>

app/views/users/public_profile.html.erb
<% if @user.public_shared_places.present? %>
<p class="text-bold">Location Shared Publicly:</p>
<ul>
  <% @user.public_shared_places.each do |place| %>
  <li><strong><%= place.address %></strong></li>
  <% end %>
</ul>
 <div id="map-for-public"></div>
<% else %>
<p>No Location Has been shared publicly by this user.</p>
<% end %>
<script>
  var publicPlaces = '<%= @public_places.html_safe  %>';
  var currentUserId = null;
</script

app/views/users/show.html.erb
<h4><%= @user.name %>'s Profile</h4>
<%= link_to "Share Location", new_place_path, class: "btn btn-primary pull-right" %>
<% if @shared_places_data.present? %>
<div id="public">
  <% if @user.public_shared_places.present? %>
    <p class="text-bold">Location Shared Publicly:</p>
      <ul>
        <% @user.public_shared_places.each do |place| %>
          <li><strong><%= place.address %></strong></li>
        <% end %>
      </ul>
  <% end %>
  <% if @user.grouped_shared_places_for_friends.present? %>
    <p class="text-bold">Location Shared With Friend:</p>
    <ul>
      <% @user.grouped_shared_places_for_friends.each do |address, shared_places| %>
        <li><strong><%= address %> </strong>is shared with <%= shared_places.collect(&:friend_name).join(", ") %></li>
      <% end %>
    </ul>
  <% end %>
  <% if @user.places_shared_with_user.present? %>
    <p class="text-bold">Location Shared With <%= name(@user) %>:</p>
    <ul>
      <% @user.grouped_places_shared_with_user.each do |address, shared_places| %>
        <li><strong><%= address %> </strong>is shared with <%= name(@user) %>.</li>
      <% end %>
    </ul>
  <% end %>
  <div id="map-for-public"></div>
</div>
<% end %>

<% if @friends.present? && current_user == @user %>
<table class="table">
  <thead>
    <tr>
	    <th>Friend</th>
	    <th class="text-right">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
    <tr>
	    <td><%= friend.name %></td>
      <td class="text-right"><%= link_to "Show Profile",  public_profile_user_path(friend.username), class: "btn" %></td>
	  </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<script>
  var publicPlaces = '<%= @shared_places_data.html_safe  %>';
  var currentUserId = '<%= raw current_user.id %>';
</script